services:
  game:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    ports:
      - "4433:4433"
      - "4433:4433/udp"
    environment:
      ENV: DEV
    volumes:
      - ./app:/app